In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

Data Understanding

In [3]:
df=sns.load_dataset('iris')
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [4]:
df.sample(10)

     sepal_length  sepal_width  petal_length  petal_width     species
3             4.6          3.1           1.5          0.2      setosa
19            5.1          3.8           1.5          0.3      setosa
133           6.3          2.8           5.1          1.5   virginica
30            4.8          3.1           1.6          0.2      setosa
95            5.7          3.0           4.2          1.2  versicolor
38            4.4          3.0           1.3          0.2      setosa
80            5.5          2.4           3.8          1.1  versicolor
15            5.7          4.4           1.5          0.4      setosa
57            4.9          2.4           3.3          1.0  versicolor
76            6.8          2.8           4.8          1.4  versicolor

In [5]:
df.shape

(150, 5)

In [6]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [7]:
X=df.drop(columns='species')
y=df['species']

In [8]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.2 KB

Data Quality Inspection

In [10]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
(df.isnull().sum()/len(df))*100

sepal_length    0.0
sepal_width     0.0
petal_length    0.0
petal_width     0.0
species         0.0
dtype: float64

In [22]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [24]:
df.value_counts().sum()

np.int64(149)

In [26]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     49
Name: count, dtype: int64

In [28]:
df['species'].nunique()

3

In [29]:
df['species'].unique()

<ArrowStringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [31]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    149.000000   149.000000    149.000000   149.000000
mean       5.843624     3.059732      3.748993     1.194631
std        0.830851     0.436342      1.767791     0.762622
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.300000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

Descriptive Statistics

In [42]:
num_cols=df.select_dtypes(include='number')

print("Mean \n",num_cols.mean())
print()
print("Median \n",num_cols.median())
print()
print("Mode \n",num_cols.mode())
print()
print("Std \n",num_cols.std())
print()

Mean
 sepal_length    5.843624
sepal_width     3.059732
petal_length    3.748993
petal_width     1.194631
dtype: float64

Median
 sepal_length    5.8
sepal_width     3.0
petal_length    4.3
petal_width     1.3
dtype: float64

Mode
    sepal_length  sepal_width  petal_length  petal_width
0           5.0          3.0           1.4          0.2
1           NaN          NaN           1.5          NaN

Std
 sepal_length    0.830851
sepal_width     0.436342
petal_length    1.767791
petal_width     0.762622
dtype: float64

In [43]:
print("Min \n",num_cols.min())
print()
print("Max \n",num_cols.max())
print()
print("Range \n",num_cols.max()-num_cols.min())
print()

Min
 sepal_length    4.3
sepal_width     2.0
petal_length    1.0
petal_width     0.1
dtype: float64

Max
 sepal_length    7.9
sepal_width     4.4
petal_length    6.9
petal_width     2.5
dtype: float64

Range
 sepal_length    3.6
sepal_width     2.4
petal_length    5.9
petal_width     2.4
dtype: float64

In [44]:
print("Q1 ",num_cols.quantile(.25))
print()
print("Q2 ",num_cols.quantile(.50))
print()
print("Q3 ",num_cols.quantile(.75))
print()

Q1  sepal_length    5.1
sepal_width     2.8
petal_length    1.6
petal_width     0.3
Name: 0.25, dtype: float64

Q2  sepal_length    5.8
sepal_width     3.0
petal_length    4.3
petal_width     1.3
Name: 0.5, dtype: float64

Q3  sepal_length    6.4
sepal_width     3.3
petal_length    5.1
petal_width     1.8
Name: 0.75, dtype: float64

In [46]:
mean=num_cols.mean()
median=num_cols.median()
diff=mean-median
print(diff)

sepal_length    0.043624
sepal_width     0.059732
petal_length   -0.551007
petal_width    -0.105369
dtype: float64

In [48]:
df.describe().T

              count      mean       std  min  25%  50%  75%  max
sepal_length  149.0  5.843624  0.830851  4.3  5.1  5.8  6.4  7.9
sepal_width   149.0  3.059732  0.436342  2.0  2.8  3.0  3.3  4.4
petal_length  149.0  3.748993  1.767791  1.0  1.6  4.3  5.1  6.9
petal_width   149.0  1.194631  0.762622  0.1  0.3  1.3  1.8  2.5

Univariate Analysis

In [50]:
df.groupby('species').size()

species
setosa        50
versicolor    50
virginica     49
dtype: int64

In [52]:
df['species'].value_counts()/len(df)

species
setosa        0.335570
versicolor    0.335570
virginica     0.328859
Name: count, dtype: float64

In [53]:
num_cols.mean().idxmin()

'petal_width'

In [55]:
num_cols.std().idxmax()

'petal_length'

In [ ]:
q1=num_cols.quantile(.25)
q3=num_cols.quantile(.75)

iqr=q3-q1

outliers=(num_cols<(q1-1.5*iqr)) | (num_cols> (q3+1.5*iqr))
outliers.sum()

In [68]:
range=num_cols.max()-num_cols.min()
range.idxmax()

'petal_length'